---
- hosts: usviproddb
  remote_user: jlouthan
  tasks:
      - name: Backup Prod Database
        shell: mysqldump usvi_drupal | gzip -9c > ~jlouthan/usvi_drupal.`date +%Y-%m-%d`.sql.gz ; ls -la ~jlouthan/ | grep `date +%Y-%m-%d`
        register: dumpprod
        become: yes
        become_method: sudo

      - debug: var=proddump.stdout_lines

      - name: Make sure that the Prod DB Backups look good before you contine
        pause: 

- hosts: ws1
  remote_user: jlouthan
  tasks:
      - name: Pull the Prod DB Backup to here
        shell: scp jlouthan@usviproddb:~/usvi_drupal.`date +%Y-%m-%d`.sql.gz ~/

      - name: Push the Prod DB Backup to usvidevdb
        shell: scp ~/usvi_drupal.`date +%Y-%m-%d`.sql.gz jlouthan@usvidevdb:~/

- hosts: usvidevdb
  remote_user: jlouthan
  tasks:
      - name: Unzip the Backup file
        shell: gunzip -f ~jlouthan/usvi_drupal.`date +%Y-%m-%d`.sql.gz
