---
- hosts: prod
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name:  Can root login through ssh?
        shell: 'cat /etc/ssh/sshd_config | grep -i PermitRootLogin'
        register: sshdPermitRootLogin

      - debug: var=sshdPermitRootLogin.stdout_lines
