---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name: Update the Locate DB
        shell: 'updatedb'

      - name: Find all instances for web.xml and place them into a file
        shell: 'locate web.xml >> /tmp/list-CVE-2017-5664'

      - name: Check tomcat version(s)
        shell: 'for i in `cat /tmp/list-CVE-2017-5664`; do grep -i "readonly=false" $i ; done'
        register: version

      - debug: var=version.stdout_lines
