---
- hosts: ws4:app27
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name: Check the RHEL version
        shell: 'cat /etc/redhat-release'
        register: version

      - debug: var=version.stdout_lines
