---
- hosts: ws4:app27
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name: Check java version 
        shell: 'java -version'
        register: version

      - debug: var=version.stdout_lines
