---
- hosts: usviproddb
  remote_user: jlouthan
  tasks:
      - name: Backup Prod Database
        shell: mysqldump usvi_drupal | gzip -9c > ~jlouthan/usvi_drupal.`date +%Y-%m-%d`.sql.gz ; ls -la ~jlouthan/ | grep `date +%Y-%m-%d`
        register: dumpprod
        become: yes
        become_method: sudo

      - debug: var=dumpprod.stdout_lines

      - name: Make sure that the Prod DB Backups look good before you continue
        pause: 

- hosts: ws1
  remote_user: jlouthan
  tasks:
      - name: Pull the Prod DB Backup to here
        shell: scp jlouthan@usviproddb:~/usvi_drupal.`date +%Y-%m-%d`.sql.gz ~/

      - name: Push the Prod DB Backup to usvidevdb
        shell: scp ~/usvi_drupal.`date +%Y-%m-%d`.sql.gz jlouthan@usvidevdb:~/

- hosts: usvidevdb
  remote_user: jlouthan
  tasks:
      - name: Unzip the Backup file
        shell: gunzip -f ~jlouthan/usvi_drupal.`date +%Y-%m-%d`.sql.gz

      - name: Backup the Staging DB
        shell: mysqldump stg_visitusvi | gzip -9c > ~/stg_visitusvi.`date +%Y-%m-%d.%H%M`.sql.gz ; ls -la ~/ | grep `date +%Y-%m-%d`
        register: dumpstg
        become: yes
        become_method: sudo

      - debug: var=dumpstg.stdout_lines

      - name: Check and see that the stg backup looks good before you continue
        pause: 

      - name: Restore prod db into staging db
        shell: mysql stg_visitusvi < ~jlouthan/usvi_drupal.`date +%Y-%m-%d`.sql

- hosts: usviprodweb1
  remote_user: jlouthan
  tasks: 
      - name: Backup the files directory
        shell: tar -czvf ~jlouthan/www.visitusvi.com-files`date +%Y-%m-%d` /var/www/sites/www.visitusvi.com/sites/default/files ; ls -la | grep `date +%Y-%m-%d`
        register: tarprodfiles
        become: yes
        become_method: sudo

      - debug: var=tarprodfiles.stdout_lines

      - name: Please check the Prod Files archive before continuing
        pause: 

- hosts: ws1
  remote_user: jlouthan
  tasks:
      - name: Pull the Prod Files archive to ws1
        shell: scp jlouthan@usviprodweb1:~/www.visitusvi.com-files`date +%Y-%m-%d` ~/

      - name: Push the Prod Files archive to ws1
        shell: scp ~/www.visitusvi.com-files`date +%Y-%m-%d` jlouthan@usvidevweb:~/

- hosts: usvidevweb
  remote_user: jlouthan
  tasks: 
      - name: Backup Staging's current files directory
        shell: mv /var/www/sites/stg-www.visitusvi.com/sites/default/files/ /var/www/sites/stg-www.visitusvi.com/sites/default/files`date +%Y-%m-%d`/
        become: yes
        become_method: sudo

      - name: Unpack the Prod Files archive
        shell: tar -xzvf ~/www.visitusvi.com-files`date +%Y-%m-%d` -C /var/www/sites/stg-www.visitusvi.com/sites/default/files/
        become: yes
        become_method: sudo

      - name: Clean up files directory
        shell: chown -R websync: /var/www/sites/stg-www.visitusvi.com/sites/default/files/ && chmod 755 /var/www/sites/stg-www.visitusvi.com/sites/default/files/ && setfacl -Rm u:apache:rwx /var/www/sites/stg-www.visitusvi.com/sites/default/files/
        become: yes
        become_method: sudo
