---
- hosts: web14
  remote_user: jlouthan
  tasks:
      - name: Install the latest version of MySQL-Python
        yum: name=MySQL-python state=latest
        become: yes
        become_method: sudo

      - name: Get current timestamp
        local_action: command bash -c 'date +%Y-%m-%d.%H%M'
        register: timestamp
        run_once: true

      - name: Get current datestamp
        local_action: command bash -c 'date +%Y-%m-%d'
        register: datestamp
        run_once: true

      - name: Drop preprod_qa_dt_pennzoil
        mysql_db: state=absent name=preprod_qa_dt_pennzoil
        become: yes
        become_method: sudo

      - name: Create preprod_qa_dt_pennzoil
        mysql_db: state=present name=preprod_qa_dt_pennzoil
        become: yes
        become_method: sudo
      
      - name: Dump qa_dt_pennzoil
        mysql_db: state=dump name=qa_dt_pennzoil target=/home/jlouthan/qa_dt_pennzoil.{{ datestamp.stdout }}.sql
        become: yes
        become_method: sudo

      - name: Import qa_dt_pennzoil into preprod_qa_dt_pennzoil
        mysql_db: state=import name=preprod_qa_dt_pennzoil target=/home/jlouthan/qa_dt_pennzoil.{{ datestamp.stdout }}.sql
        become: yes
        become_method: sudo

      - name: Search and replace FQDN (Wordpress sites only)
        shell: "/usr/local/jwt/Search-Replace-DB/srdb.cli.php -h localhost -n preprod_qa_dt_pennzoil -u root -p '' -s 'qa.pennzoil.com' -r 'www.pennzoil.com' ; /usr/local/jwt/Search-Replace-DB/srdb.cli.php -h localhost -n preprod_qa_dt_pennzoil -u root -p '' -s 'qa.pennzoil.ca' -r 'www.pennzoil.ca' ; /usr/local/jwt/Search-Replace-DB/srdb.cli.php -h localhost -n preprod_qa_dt_pennzoil -u root -p '' -s 'qa-m.pennzoil.com' -r 'm.pennzoil.com'"
        register: fqdnreplace
        remote_user: jlouthan
        become: yes
        become_method: sudo

      - debug: var=fqdnreplace.stdout_lines

      - pause: prompt='Check and see if the FQDN search and replace looks right.

      - name: Dump qa into preprod
        mysql_db: state=dump name=qa_dt_pennzoil target=/home/jlouthan/preprod_qa_dt_pennzoil.sql
        become: yes
        become_method: sudo

- hosts: web16
  remote_user: jlouthan
  tasks:
      - name: Install the latest version of MySQL-Python
        yum: name=MySQL-python state=latest
        become: yes
        become_method: sudo

      - name: Get current timestamp
        local_action: command bash -c 'date +%Y-%m-%d.%H%M'
        register: timestamp
        run_once: true

      - name: Get current datestamp
        local_action: command bash -c 'date +%Y-%m-%d'
        register: datestamp
        run_once: true

      - name: Backup Prod Database
        mysql_db: "state=dump name=wp_pennzoil target=/home/jlouthan/wp_pennzoil.{{ timestamp.stdout }}.sql"
        become: yes
        become_method: sudo

      - name: See the wp_pennzoil DB backup
        shell: ls -la /home/jlouthan/ | grep {{ datestamp.stdout }}
        register: dumpdb

      - debug: var=dumpdb.stdout_lines

      - pause: prompt='Make sure that the prod backups look good before you continue'

      - name: Move preprod dump from qa to prod
        shell: rsync -av web14:/home/jlouthan/preprod_qa_dt_pennzoil.sql /home/jlouthan/

      - name: Restore Prod DT DB from Preprod QA DT DB
        mysql_db: state=import name=wp_pennzoil target=/home/jlouthan/preprod_qa_dt_pennzoil.sql
        become: yes
        become_method: sudo

- hosts: web12:web13
  remote_user: jlouthan
  tasks:
      - name: rsync uploads/ from qa to prod
        shell: rsync -av web14:/var/www/qa.pennzoil.com/public/wp-content/uploads/ /var/www/www.pennzoil.com/public/wp-content/uploads/
        become: yes
        become_user: websync
        become_method: sudo

      - name: rsync blogs.dir/ from qa to prod
        shell: rsync -av web14:/var/www/qa.pennzoil.com/public/wp-content/blogs.dir/ /var/www/www.pennzoil.com/public/wp-content/blogs.dir/
        become: yes
        become_user: websync
        become_method: sudo

      - name: Restart varnish
        service: name=varnish state=restarted
        become: yes
        become_method: sudo
