---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
        - name: Make authkeys 700
          file: path=/home/{{  item  }}/.ssh/authorized_keys mode=0700
          with_items:
            - kchu
            - bbeecroft
            - mhiivala
            - kmasud
