---
- hosts: semperfi1:semperfi2
  remote_user: jlouthan
  tasks:
      - name:  Get expiration information for all accounts
        shell: 'ls -1 /var/www/sites/*/'
        register: find
        become: yes
        become_method: sudo

      - debug: var=find.stdout_lines
