---
- hosts: web
  remote_user: jlouthan
  become: yes
  become_method: sudo
  
  tasks:
      - name:  Find websites
        shell: 'ls -la /var/www/ | grep {{  item  }}'
        with_items:
          - qa-connect.marines.com
