---
- hosts: all
  remote_user: jlouthan
  tasks:
      - name:  Find the process
        shell: "ps ef | grep httpd | grep -v grep | awk '{ print $7 }'"
        register: ps
        become: yes
        become_method: sudo

      - debug: var=ps.stdout_lines
