---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name:  Find websites
        shell: 'locate -e {{  item  }}'
        loop:
          - mailer.marines.com
        register: locate

      - debug: var=locate.stdout_lines
