---
- hosts: pwn:pc11:qs:pnz
  remote_user: jlouthan
  tasks:
      - name:  Get expiration information for all accounts
        shell: 'cut -f 1 -d: /etc/passwd | xargs -n 1 -I {} bash -c " echo {} ; chage -l {}"'
        register: chage
        become: yes
        become_method: sudo

      - debug: var=chage.stdout_lines
