---
- hosts: web1:web2:web3
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name: Install libpwquality
        yum: name=libpwquality state=latest

      - name: Create /root/Backup
        file: path=/root/Backup state=directory

      - name: Backup system-auth
        shell: 'cp /etc/pam.d/system-auth /root/Backup/system-auth`date +%Y%m%d.%H%M`'

      - name: Comment out cracklib line and insert pwquality line after it
        shell: "grep -q pam_cracklib.so /etc/pam.d/system-auth && sed -e '/pam_cracklib.so/ s/^#*/#/' -i /etc/pam.d/system-auth && sed -i '/pam_cracklib.so/a password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 type= remember=40' /etc/pam.d/system-auth"
