---
- hosts: stgweb1-ep:stgweb2-ep
  remote_user: jlouthan
  become: yes
  become_user: websync
  become_method: sudo
  
  tasks:
        - name: pm2 restarting...
  #        command: pm2 restart {{ my_webapp }}
          script: "scripts/restartqamailer.sh"
          register: pm2
          args:
            executable: /usr/local/bin/node

        - debug: var=pm2.stdout_lines
