---
- hosts: proxy1:proxy2:proxy3:proxy4
  remote_user: jlouthan
  become: yes
  become_method: sudo
  
  tasks:
      - name: Restart varnish
        service: name=varnish state=restarted

      - name: Check process
        shell: ps -e | grep varnish | awk '{print $4}'
        register: procvarnish

      - debug: var=procvarnish.stdout_lines

      - pause: prompt='Do you see two (2) varnishd, one (1) log, and one (1) ncsa?'
