---
- hosts: pc11web1:pc11web2
  remote_user: jlouthan
  tasks:
      - name: Restart varnish
        service: name=varnish state=restarted
        remote_user: jlouthan
        become: yes
        become_method: sudo
