---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo
  tasks:
      - name: All the sites for all the servers
        find:
                paths: /var/www/
                file_type: directory        
                patterns: '*.com'
                recurse: yes
