---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name: Remove username from sudoers
        replace:
                path: /etc/sudoers
                regexp: ', ckemp'
                replace: ''
                backup: yes

      - name: Remove username from sudoers
        replace: 
                path: /etc/sudoers
                regexp: 'ckemp,'
                replace: ''
                backup: yes
