---
- hosts: ws1
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name: Create account
        user: name=nicholaus.perez shell=/bin/bash home=/home/nicholaus.perez/

      - name: Unexpire account
        user: name=nicholaus.perez expires=0

      - name: Copy .ssh directory
        copy:
                src=/home/jlouthan/Playbooks/home/nicholaus.perez/.ssh/
                dest=/home/nicholaus.perez/.ssh/ 
                owner=nicholaus.perez 
                group=nicholaus.perez 
                directory_mode=744
