---
- hosts: ws1
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
        - name: Adding mirumwheel (whoops!) group
          group: name=mirumwheel state=present

        - name: Create users
          user: name={{  item.name  }} state=present groups=mirumwheel password={{  item.pass  }}  shell='/bin/bash'
          with_items:
                 - { name: 'rchavez' , pass: '$6$rounds=656000$z1BQWWZI.dpe0967$fRZFwqJwkpSMl9Ecm3lHSBL8Onzz1vIsh7kzMkniq7BpcGrqKrRhUJavM.Br8Jc2Dk3/1PkrmmefPC8s4l36V/' }
                
        - name: Expire account
          command: "chage -I 30 -M 60 {{  item  }}"
          with_items:
            - rchavez

        - name: Create .ssh directory
          file: path=/home/{{  item  }}/.ssh/ state=directory mode=0700 owner={{  item  }} group={{  item  }}
          with_items:
            - rchavez

        - name: Copy authkeys to .ssh dirs
          copy: src=authkeys/{{  item  }} dest=/home/{{  item  }}/.ssh/authorized_keys owner={{  item  }} group={{  item  }} mode=0600
          with_items:
            - rchavez
