---
- hosts: ws3
  remote_user: jlouthan
  vars:
        # created with
        # python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
        password: $6$YKstaElZ$lFCA14FC3F5BmuOhFexWvTu0ycTei6bSsEyVq9kEnFPY0RVN0N/yOaKgK2WgZrBHbw3Xc0I89EcQckGWnZjZW/

  tasks:
      - name: Reset password
        user: name=rchavez password={{ password }}
        become: yes
        become_method: sudo 
