---
- hosts: aem
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
        - name: Create users
          user: name={{  item.name  }} state=present password={{  item.pass  }}  shell='/bin/bash'
          with_items:
                 - { name: 'nicholaus.perez' , pass: '$6$rounds=656000$DXay8fNQ/X6iq4kO$a9XV2gh8hEUQgtxn8KwvdIUigRyqKN8uXuDu9HnkoMFLdsjAPzCp1yQK4znhG4xK3GbD6zGJsQhJzGt0s7SQx0' }
                
        - name: Expire account
          command: "chage -I 30 -M 60 {{  item  }}"
          with_items:
            - nicholaus.perez

        - name: Create .ssh directory
          file: path=/home/{{  item  }}/.ssh/ state=directory mode=0700 owner={{  item  }} group={{  item  }}
          with_items:
            - nicholaus.perez

        - name: Copy authkeys to .ssh dirs
          copy: src=authkeys/{{  item  }} dest=/home/{{  item  }}/.ssh/authorized_keys owner={{  item  }} group={{  item  }} mode=0600
          with_items:
            - nicholaus.perez
