---
- hosts: ws3
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name:  Get Disk Space information on all mounts
        shell: 'mysql -V'
        register: version

      - debug: var=version.stdout_lines
