---
# Set timestamp
- hosts: web14
  remote_user: jlouthan

# Backup Prod Databases
  tasks:
      - name: Backup Prod Databases
        shell: "for DB in wp_pennzoil mobile_pennzoil  ; do mysqldump $DB | gzip -9c > ~/$DB.`date +%Y-%m-%d.%H%M`.sql.gz ; done ; l ~/ | grep `date +%Y-%m-%d`"
        register: mysqldump
        remote_user: jlouthan
        become: yes
        become_method: sudo

      - debug: var=mysqldump.stdout_lines
