---
- hosts: ws3:!ftp:!ftp1:!ftp2
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name: Backing up /etc/login.defs
        shell: 'cp /root/test/login.defs /root/test/login.defs`date +%Y%m%d.%H%M`'

      - name: Backing up useradd
        shell: 'cp /root/test/useradd /root/test/useradd`date +%Y%m%d.%H%M`'

      - name: Changing Minimum Days for Password to 1
        shell: 'grep -q ^PASS_MIN_DAYS /root/test/login.defs && sed -i "s/PASS_MIN_DAYS.*/PASS_MIN_DAYS     1/g" /root/test/login.defs ; if ! [ $? -eq 0 ]; then echo "PASS_MIN_DAYS      1" >> /root/test/login.defs ; fi'

      - name: Changing Maximum Days for Password to 60
        shell: 'grep -q ^PASS_MAX_DAYS /root/test/login.defs && sed -i "s/PASS_MAX_DAYS.*/PASS_MAX_DAYS     60/g" /root/test/login.defs ; if ! [ $? -eq 0 ]; then echo "PASS_MAX_DAYS     60" >> /root/test/login.defs ; fi'

      - name: Changing Minimum Length of password to 8
        shell: 'grep -q ^PASS_MIN_LEN /root/test/login.defs && sed -i "s/PASS_MIN_LEN.*/PASS_MIN_LEN     8/g" /root/test/login.defs ; if ! [ $? -eq 0 ]; then echo "PASS_MIN_LEN      8" >> /root/test/login.defs ; fi'

      - name: Changing to Maximum Days of Warning to 7
        shell: 'grep -q ^PASS_WARN_AGE /root/test/login.defs && sed -i "s/PASS_WARN_AGE.*/PASS_WARN_AGE     7/g" /root/test/login.defs ; if ! [ $? -eq 0 ]; then echo "PASS_WARN_AGE      7" >> /root/test/login.defs ; fi'

      - name: Changing the number of Inactive days to 30
        shell: 'grep -q ^INACTIVE= /root/test/useradd && sed -i "s/INACTIVE=.*/INACTIVE=30/g" /root/test/useradd ; if ! [ $? -eq 0 ]; then echo "INACTIVE=30" >> /root/test/useradd ; fi'
