---
- hosts: util1
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name: Add a new line with comment
        lineinfile: "dest=/etc/sudoers state=present line='\n#Adding the miriumwheel group for the Mirium SysAdmins'"
      - name: Adding miriumwheel line
        lineinfile: "dest=/etc/sudoers state=present line='%miriumwheel  ALL=(ALL)       ALL'"
