---
- hosts: ws1
  remote_user: jlouthan
  tasks:
      - name: Check usernames
        command: cut -d':' -f1 /etc/passwd
        register: wheel
        become: yes
        become_method: sudo

      - debug: var=wheel.stdout_lines
