---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo
  tasks:
      - name: Unlock account
        command: passwd -u secops

      - name: Delete password
        command: passwd -d secops

      - name: Unexpire account
        user: name=secops expires=0

      - name: Copy authorized_keys
        copy: src=/home/secops/.ssh/authorized_keys dest=/home/secops/.ssh/authorized_keys owner=secops group=secops mode="u+rwx,g-rwx,o-rwx"
