---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
        - name: Create users
          user: name={{  item.name  }} state=present groups=wheel password={{  item.pass  }}  shell='/bin/bash'
          with_items:
                 - { name: 'jbyers' , pass: '$6$rounds=656000$npdJ5jzvQ8QkEEgl$3804VKfMDxMr9Vcz0cjCdPiGANRHwNf0pSw7/0erOaqinFAY5U68Z35eAMHodBkdFIEI9N4GuAroVRZIhBRX11' }
                
        - name: Expire account
          command: 'chage -I 30 -M 60 -E -1 {{  item  }}'
          with_items:
            - jbyers

        - name: Create .ssh directory
          file: path=/home/{{  item  }}/.ssh/ state=directory mode=0700 owner={{  item  }} group={{  item  }}
          with_items:
            - jbyers

        - name: Copy authkeys to .ssh dirs
          copy: src=authkeys/{{  item  }} dest=/home/{{  item  }}/.ssh/authorized_keys owner={{  item  }} group={{  item  }} mode=0600
          with_items:
            - jbyers
