---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo
  tasks:
      - name: Unlock account
        command: passwd -u secops

      - name: Unexpire account
        command: "chage -I -1 -M -1 -E -1 secops"
