---
- hosts: all:!ws1
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
        - name: Copy authkeys to .ssh dirs
          copy: src=authkeys/{{  item  }} dest=/home/{{  item  }}/.ssh/authorized_keys owner={{  item  }} group={{  item  }} mode=0700
          with_items:
            - ckemp
