---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo
  tasks:
      - name: Change password
        user: name={{  item.name  }} password={{  item.pass  }}#
        with_items:
           - { name: 'srudra', pass: '$6$rounds=656000$Vm30Wg4W5Tb0RxpW$OotJRNf7puGlal.H4bV6mi/aABzB5k/TI8.A0lrfnySBUtTu5uTU/CtkX.beqE3gJm3lcs1GJ5IrN/bJDM4G.0' }

      - name: Unlock account
        command: passwd -u srudra

      - name: Unexpire account
        command: "chage -I 30 -M 60 -E -1 srudra"

#      - name: Copy authorized_keys
#        copy: src=authkeys/srudra dest=/home/srudra/.ssh/authorized_keys owner=srudra group=srudra mode="u+rwx,g-rwx,o-rwx"
