---
- hosts: usvi8
  remote_user: jlouthan
  become: yes
  become_method: sudo
  tasks:
      - name: Change password
        user: name={{  item.name  }} password={{  item.pass  }}
        with_items:
           - { name: 'ckemp', pass: '$6$rounds=656000$NqyBGppyyuCQmiF1$5sX8nvm81IjFXwQpch//aJ2AEAcMqfTa.ze4LCS4fNOoZKIta9Y/xxM105kAcfSSRKIehSzkIHRkDlKF6M1Qc.' }

      - name: Unlock account
        command: passwd -u ckemp

      - name: Expire account
        command: "chage -I 30 -M 60 -E -1 ckemp"

#      - name: Copy authorized_keys
#        copy: src=authkeys/ckemp dest=/home/ckemp/.ssh/authorized_keys owner=ckemp group=ckemp mode="u+rwx,g-rwx,o-rwx"
