---
- hosts: phantom
  remote_user: jlouthan
  become: yes
  become_method: sudo
  vars:
        # created with
        # python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
        password: $6$rounds=656000$GHaROnXzXPRLR8nN$KVor.hdLTd1nQNzOTP/Qn7g.nKONZME/t3nH4K8fU6BfVg9onxQbDs/VV1TW69CijzbTB.vMujy61AJTpEW7i.

  tasks:
      - name: Reset password
        user: name=ckemp password={{ password }}
