---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo
  vars:
        # created with
        # python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
        password: $6$rounds=656000$KbUJG7KLO/OIUVMs$TVJ9k8/fUFfG/nOTMza0oFsIxSssVqlWpQajKUz9SuUXKaJikd8JjyfoyJPDSTGBnp9PRFmmmVpJCkwTviHUm1

  tasks:
      - name: Reset password
        user: name=jlouthan password={{ password }}
