---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo
  tasks: 
#      - name: Remove files from current bwilliams .ssh dir
#        command: rm -f /home/bwilliams/.ssh/*

      - name: Create .ssh within homedir


      - name: Copy authorized_keys file
        file: path=/home/bwilliams/.ssh/authorized_keys state=touch mode=0700

      - name: Insert new key
        shell: echo "" >> /home/bwilliams/.ssh/authorized_keys
