---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
        - name: Create users
          user: name={{  item.name  }} state=present groups=mirumwheel password={{  item.pass  }}  shell='/bin/bash'
          with_items:
                 - { name: 'lleung' , pass: '$6$rounds=656000$.A/xjojfdiwg9hXJ$0w8xwOkUFi3a50acUBwgI0SIY.dmUisGwxLkmwbQr3PJkBJd90729.0ALhNq3lLovmp.iCPB6IdpTVT4JiTBH/' }
                
        - name: Expire account
          command: 'chage -I 7 -M 60 -E "2017-07-25" -W 3 {{  item  }}'
          with_items:
            - lleung

        - name: Create .ssh directory
          file: path=/home/{{  item  }}/.ssh/ state=directory mode=0700 owner={{  item  }} group={{  item  }}
          with_items:
            - lleung

        - name: Copy authkeys to .ssh dirs
          copy: src=authkeys/{{  item  }} dest=/home/{{  item  }}/.ssh/authorized_keys owner={{  item  }} group={{  item  }} mode=0600
          with_items:
            - lleung
