---
- hosts: aem
  remote_user: jlouthan
  become: yes
  become_method: sudo
  vars:
        # created with
        # python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
        password: $6$rounds=656000$kiBWFZAgl0/InrFG$9.644ltQRxJiatp6b875zioY/ZlcIIW2YrTyHBR0muBehVSk3g/EMdAsjrP7joJ21chxBtT6IZlvtI4Snn6wY.

  tasks:
      - name: Reset password
        user: name=jlouthan password={{ password }}
