---
- hosts: web1-ep:web2-ep
  remote_user: jlouthan
  become: yes
  become_method: sudo
  tasks:
      - name: Change password
        user: name={{  item.name  }} password={{  item.pass  }}#
        with_items:
           - { name: 'bwilliams', pass: '$6$rounds=656000$WeGOzpyUQxEuXLD7$OZkRkHQ8VnA45.WhOknTgW.pt/SSgw3NUPvJoXKebiw8yiv/qj6Sppp8pmu62BL0aBdHo9yc9zqC/nAzce4Vl0' }

      - name: Unlock account
        command: passwd -u bwilliams

      - name: Expire account
        command: "chage -I -1 -M -1 -E -1 bwilliams"

#      - name: Copy authorized_keys
#        copy: src=authkeys/bwilliams dest=/home/bwilliams/.ssh/authorized_keys owner=bwilliams group=bwilliams mode="u+rwx,g-rwx,o-rwx"
