---
- hosts: app30:ws1
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
        - name: Create users
          user: name={{  item.name  }} state=present groups=wheel password={{  item.pass  }}  shell='/bin/bash'
          with_items:
                 - { name: 'dhalliyur' , pass: '$6$rounds=656000$6NPfGW5eG0Yj7y3D$k/DtENUDwp.q/QO3B6489nMkikcByV1PdKyxOCDFhf9G3Mym0GWpj7FH0GxN4Yt/MYwHqtNbaXvJluODFOWZu.' }
