---
- hosts: all
  remote_user: jlouthan
  vars:
        # created with
        # python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
        password: $6$rounds=656000$Ym80H.sRKH2YeUQX$Wuhkp6nwHuMxwg/OG7aizksCtR0wgsPdTX/jwpuqKsmmnocQRIrozdpd1c8lbebaSZMV9monid63oH0N8LK1W.
  tasks:
      - name: Reset password
        user: name=jlouthan password={{ password }}
        become: yes
        become_method: sudo 
