---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo 

  tasks:
      - name: Adding mirumwheel group
        group: name=mirumwheel state=present

      - name: Add user to mirumwheel group
        user: name={{  item  }} groups=mirumwheel
        with_items:
         - bbeecroft
         - mhiivala
         - kchu
         - kmasud
         - rchavez
