---
- hosts: aem
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
        - name: Change password
          user: name={{  item.name  }} password={{  item.pass  }}
          with_items:
                 - { name: 'bahamat', pass: '$6$rounds=656000$Xzcrgp4TgFA6ibK3$bylNasVjuulIxrML.iOJKWnlGl4lEQ4UP.r88TIrqD3fDEGFk2VoOuz6VNaIditXayc.omhpb73yWZH8xAoZZ1' }
