---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
        - name: Change password
          user: name={{  item.name  }} password={{  item.pass  }}
          with_items:
                 - { name: 'jlouthan', pass: '$6$rounds=656000$5iqgLEiEAfvtPt0t$SMfMxvAv1BU0GlRfzHCRL1PNNDjtFVN8oVnIadhoB2For4lmGCHYWAd9kFJVBXmAgPjzl6h.joxba6GQqHuYz0' }
