---
- hosts: ws1
  remote_user: jlouthan
  become: yes
  become_method: sudo
  tasks:
      - name: Change password
        user: name={{  item.name  }} password={{  item.pass  }}#
        with_items:
           - { name: 'jburns', pass: '$6$rounds=656000$WTHITYa1pzGrn56o$jfylfChSvc1r7rHf7KFFhmBsRTpPv1QpWsMLFTQiK2.DB6HnFM/NRJb5jEPEdX6x4UTo.Z9WIpqUjVrWgciLF.' }

      - name: Unlock account
        command: passwd -u jburns

      - name: Unexpire account
        command: "chage -I -1 -M -1 -E -1 jburns"

#      - name: Copy authorized_keys
#        copy: src=authkeys/jburns dest=/home/jburns/.ssh/authorized_keys owner=jburns group=jburns mode="u+rwx,g-rwx,o-rwx"
