---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo
  tasks:
      - name: Lock account
        command: passwd -l jbesadesky
        remote_user: jlouthan
        become: yes
        become_method: sudo

      - name: Expire account
        user: name=jbesadesky expires=1
        remote_user: jlouthan
        become: yes
        become_method: sudo
       
      - name: Remove keys
        command: rm -f /home/jbesadesky/.ssh/authorized_keys
        remote_user: jlouthan
        become: yes
        become_method: sudo 
