---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo
  vars:
        # created with
        # python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
        password: $6$rounds=656000$F7qs4xcyqZInMCnJ$iPcQknimYrhBmyLiMN0MFzdu86X6VkI/Z.5cabu4LOTwP3hGKfmbg/2d5xtZN9hNtP2mAlVvvRbsSx0ENU03w/

  tasks:
      - name: Reset password
        user: name=jlouthan password={{ password }}
