---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
        - name: Create users
          user: name={{  item.name  }} state=present groups=wheel password={{  item.pass  }}  shell='/bin/bash'
          with_items:
                 - { name: 'jlouthan' , pass: '$6$rounds=656000$zlrIue74Th.ZOEh0$isQoO77.lXdHzUAvCpXDAtD.SFyHJMeAS/nYnDmUZoCMCDpQhY0g8YiT.WOdGBzo6IUU5uwca1kCCLoooyo5q0' }
